- alias: "007_Hallway_turn_on_light"
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.door_window_contact_sensor_hallway_contact
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.auto_light_on_off_hallway
    state: 'on'
  - condition: and
    conditions:
     - condition: state
       entity_id: switch.0x54ef4410008178c4_switch_right
       state: 'off'
    #  - condition: state
    #    entity_id: binary_sensor.kam02_home_cell_motion_detection
    #    state: 'off'
       for:
         minutes: 10
  action:
  - service: switch.turn_on
    entity_id: switch.0x54ef4410008178c4_switch_right
    
- alias: "007_Hallway_turn_off_light_5_min_(no_motion)"
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.human_body_movement_hallway_occupancy
      to: 'off'
      for:
        minutes: 5
  condition:
  - condition: state
    entity_id: input_boolean.auto_light_on_off_hallway
    state: 'on'
  - condition: and
    conditions:
    - condition: state
      entity_id: switch.0x54ef4410008178c4_switch_right
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.0x54ef4410008178c4_switch_right
      
## Запись последнего движения в коридоре
- alias: "007_motion_hallway_time"
  initial_state: true
  trigger:
## Движение в коридоре
  - platform: state
    entity_id: binary_sensor.human_body_movement_hallway_occupancy
    to: 'on'
  condition: []
  action:
  - service: mqtt.publish
    data_template:
      topic: "binary_sensor/158d00010f8920"
      payload: "{{ states('sensor.date_time')}}"
      retain: true
      
## Запись последнего открытия входной двери
- alias: "007_motion_hallway_time"
  initial_state: true
  trigger:
## Открытие входной двери
  - platform: state
    entity_id: binary_sensor.door_window_contact_sensor_hallway_contact
    to: 'on'
  condition: []
  action:
  - service: mqtt.publish
    data_template:
      topic: "binary_sensor/prxine9ptea758sx"
      payload: "{{ states('sensor.date_time')}}"
      retain: true
      
