- alias: "030_Semen_left_home_notification"
  trigger:
  - platform: zone
    entity_id: person.semen
    zone: zone.home
    event: leave
  condition: []
  action:
    service: telegram_bot.send_message
    data:
      message: "Семён покинул домашнюю зону 🏃️"

- alias: "030_Semen_enter_home_notification"
  trigger:
  - platform: zone
    entity_id: person.semen
    zone: zone.home
    event: enter
  condition: []
  action:
    service: telegram_bot.send_message
    data:
      message: "Семён в домашней зоне 🏡 🧨🧨🧨"
      
- alias: "030_Semen_enter_bus_stop_notification"
  trigger:
  - platform: zone
    entity_id: person.semen
    zone: zone.ostanovka_riabikova
    event: enter
  condition: []
  action:
    service: telegram_bot.send_message
    data:
      message: "Семён на остановке 🚌 🚦"
      
- alias: "030_Semen_left_bus_stop_notification"
  trigger:
  - platform: zone
    entity_id: person.semen
    zone: zone.ostanovka_riabikova
    event: leave
  condition: []
  action:
    service: telegram_bot.send_message
    data:
      message: "Семён покинул остановку 🚌 🚦"
      
- alias: "030_Semen_enter_school_notification"
  trigger:
  - platform: zone
    entity_id: person.semen
    zone: zone.shkola_markova
    event: enter
  condition: []
  action:
    service: telegram_bot.send_message
    data:
      message: "Семён в школе 🎉🎉🎉 🏨"
      
- alias: "030_Semen_left_school_notification"
  trigger:
  - platform: zone
    entity_id: person.semen
    zone: zone.shkola_markova
    event: leave
  condition: []
  action:
    service: telegram_bot.send_message
    data:
      message: "Семён покинул школу 🏃😃️"