- alias: 035_Считана_метка_Rfid1
  description: ""
  trigger:
   - platform: tag
     tag_id: "4251044132"
  condition: []
  action:
    - service: media_player.play_media
      entity_id: 
        - media_player.yandex_station_540078920110102034cf
        - media_player.yandex_station_m003nh2007vwab
      data:
          media_content_type: text
          media_content_id: 'Жопа'