- platform: systemmonitor
  resources:
  - type: processor_use
  - type: disk_use_percent
    arg: /
  - type: memory_use_percent
  - type: last_boot
  - type: disk_free
    arg: /

- platform: command_line
  name: CPU Temp
  command: "cat /sys/class/thermal/thermal_zone2/temp"
  unit_of_measurement: "°C"
  value_template: '{{ (value | multiply(0.001)) | round(1) }}'
  
- platform: time_date
  display_options:
      - 'time'
      - 'date'
      - 'beat'
      - 'date_time'


# - platform: command_line
#   name: supervisor_updates
#   command: 'curl http://supervisor/supervisor/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version,"update_available":.data.update_available,"addons":[.data.addons[] | select(.update_available)]}'''
#   value_template: "{{ value_json.addons | length }}"
#   unit_of_measurement: доступно обновлений
#   json_attributes:
#   - update_available
#   - newest_version
#   - current_version
#   - addons


